[package]
name = "bmp-protocol"
version = "0.1.1"
authors = ["Cameron Daniel <cam.daniel@gmail.com>"]
edition = "2018"

[dependencies]
bgp-rs = { git = "https://github.com/ccakes/bgp-rs", rev = "3fc910e" }
# bgp-rs = { path = "../bgp-rs" }
byteorder = { version = "1.3", features = ['i128'] }
hashbrown = "0.5"
log = "0.4"
